### ISSUE TITLE
[Bug] - Exiting room

### ISSUE THREAD

**Issue by silentaim** [kai123456/GeekFantasy#101]
Small issue - when you are leaving a room there is a fade out animation and you can't move your player. During this time your player can still be hit by incoming projectiles.

**Comment by suhuboice** [comment]
Sorry. I am confused. Our figure can move when fading out the scene. Can you provide the detail of the bug?

**Comment by kai123456** [comment]
I have test out, when you exit the room and during the fade out animation, the player can still move. However, if player gets hit before he exits, he will still takes damage, which is normal.
