### ISSUE TITLE
[BUG] Player attacks stopped when under geometry

### ISSUE THREAD

**Issue by natebud** [kai123456/GeekFantasy#109]
When the player character is both positioned directly south/under any piece of geometry and also touching that piece of geometry the book attack is stopped.

I noticed this when standing near things such as desks, walls, or bookshelves and it only works if you are standing directly below an object. When the player attacks the book only appears for a second before disappearing. It does not fly away from the player like it normally does. 

I figure this is because the player collider is placed at the character's feet so as to appear like he's standing in front of objects, but the spawn point for the book is situated somewhere near the torso. The books are programmed to despawn when in contact with the geometry. But since the spawnpoint of the book set to the torso intersects the geometry of the object when underneath it, the book instantly despawns when you fire.

**Comment by jackgao96** [comment]
Thanks for your report and we really appreciate it. We will fix this as soon as we can. Thanks again!
