### ISSUE TITLE
[Feature Request] Add current task key

### ISSUE THREAD

**Issue by cb56** [kai123456/GeekFantasy#111]
This is for 442 collaboration. I think there should be current tasks, that you can view by pressing a key on the keyboard. The game is already fun and looks great, I just thought it was missing a little bit of structure.

**Comment by jackgao96** [comment]
Thanks for your report and we will consider your suggestion.

**Comment by xkzink** [comment]
We have add a new task where player need to eliminated all the enemy in the campus building and collect 7 keys to able to enter the boss room.
