### ISSUE TITLE
Help issue of Hui

### ISSUE THREAD

**Issue by jackgao96** [kai123456/GeekFantasy#32]
// I need have with reloading game. I can't achieve the function of reloading game. I try to use 'scenceManager.loadScence' to reloading game, but there would be a bug that the player can't move anymore. //

Here I change my help wanted task. In our game, we design the player could change his weapon when his level up. I need help to design a weapon.

**Comment by hartloff** [comment]
This task need to be improved. You cannot expect an outside developer to complete a task that the team itself cannot complete. Please change to be a reasonable task for an outside developer.

**Comment by jackgao96** [comment]
Here I change my help wanted task. In our game, we design the player could change his weapon when his level up. I need help to design a weapon.
