### ISSUE TITLE
Help issue of Shuo

### ISSUE THREAD

**Issue by suhuboice** [kai123456/GeekFantasy#35]
Since I can't pause the music and we didn't have the music control button, I decided to add music for next release. Please help with pause music and change bgm when scene changed. 
I also have problems with enemy design. Please help with idea and sketch of final boss if possible.

**Comment by jayeni** [comment]
Completed pause music the game music pauses when u go to the pause menu and starts when u continue in my repo

**Comment by suhuboice** [comment]
You did not create a pull request so I cannot figure out what did you do.
