### ISSUE TITLE
[BUG] the character can stand on the flowers

### ISSUE THREAD

**Issue by kolung** [kai123456/GeekFantasy#41]
The character shouldn't stand on these objects.

![image](https://user-images.githubusercontent.com/36254190/38064238-fb8811b0-32ca-11e8-908f-df5bd6523d7f.png)
![8919be60a09351a8d741baa036d2e328](https://user-images.githubusercontent.com/36254190/38064244-01a87ea4-32cb-11e8-9128-bdc1c5e89093.png)

**Comment by suhuboice** [comment]
Thank you for report the bug

**Comment by kai123456** [comment]
bugs fixed
