### ISSUE TITLE
[Bug Reporting Activity] Some bugs in the game

### ISSUE THREAD

**Issue by ziangzha** [kai123456/GeekFantasy#42]
1.The character can go through one of the car, as the character can't cross other cars, except this one:

![qq 20180329104707](https://user-images.githubusercontent.com/36140953/38067449-50b94522-333f-11e8-9be9-f86cc9ec870c.png)

2. I'm not sure but I didn't find the way that can let the character come out after he entered in this building?

![qq 20180329111843](https://user-images.githubusercontent.com/36140953/38068295-07f40760-3343-11e8-920e-4251aeb47d51.png)

![qq 20180329110435](https://user-images.githubusercontent.com/36140953/38068018-7367f6fc-3341-11e8-9f47-6b76bdcce925.png)

**Comment by kai123456** [comment]
Thank you for the report on the car. 
However, the second one is mean to be the BOSS room, we designed to make him can not escape.

**Comment by kai123456** [comment]
bug fixed
