### ISSUE TITLE
[Feature Request] Mini Map and an instruction to get in the building or car in "Control"

### ISSUE THREAD

**Issue by darasy** [kai123456/GeekFantasy#89]
Hi, first of all, this is like the best game so far to me. Great Job!
I am writing to request a feature for this game. There should be a mini map listed on screen for the player to know where they are, and how they can go to the location that they want to. Otherwise, it takes some times to figure out myself on how to go from one location to another. Also, there should be an instruction on how to get in the car in Control, which is button 'F' (currently I don't see that among the instructions in Control).

**Comment by jackgao96** [comment]
Thanks for your request and we think it's really a good point. We will try our best to improve that.
