### ISSUE TITLE
[Feature Request] Show enemy health and slow down attacks.

### ISSUE THREAD

**Issue by briandoyle89** [kai123456/GeekFantasy#93]
There is no way to tell how close an enemy is to dying.  This is very stressful, especially with how difficult it is to kill them.  Perhaps also slow down the speed of their projectiles or make them holm in a bit less, it's very difficult to kill even one enemy.

**Comment by suhuboice** [comment]
I have modified your title as feature request. We will consider add enemy health and adjust the attacks. Thank you for your advice.

**Comment by kai123456** [comment]
feature added
