### ISSUE TITLE
[Trivial Bug] Player sprite appears under trees, potted plants, etc.

### ISSUE THREAD

**Issue by senaarma** [kai123456/GeekFantasy#94]
If the player walks into a tree or a potted plant the player sprite will end up under the tree sprite. 
![trivialbug_playersprite](https://user-images.githubusercontent.com/32111956/38910024-6aa7398e-4295-11e8-858f-c1af6056c04d.png)

**Comment by suhuboice** [comment]
Thank you for reporting.
